apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsdemo-deployment
  labels:
    app: devopsdemo
spec:
  replicas: 2         
  selector:
    matchLabels:
      app: devopsdemo
  template:
    metadata:
      labels:
        app: devopsdemo
    spec:
      containers:
      - name: devopsdemo
        image: kubernetesdotnetdevopsdemo:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"